version: '3.7'
services:
  #zimzam:
  #  container_name: zimzam
  #  image: node:latest
  #  restart: always
  #  build:
  #    dockerfile: ./Dockerfile.zimzam
  #  depends_on:
  #    - mongodb
  #  ports: 
  #    - "4200:4200"
  #    - "3000:3000"

  #ws-zimzam:
  #  container_name: zimzam
  #  image: node:latest
  #  restart: always
  #  ports: 
  #    - "4201:4201"
  #    - "80:80"

  #price-fetcher:
  #  container_name: price-fetcher
  #  image: node:latest
  #  restart: always
  #  ports: 
  #    - "4202:4202"


  mongodb:
    container_name: mongodb-zimzam
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongodb-data: